# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAc < Formula
  desc "An autocomplete wrapper for kubectl"
  homepage "https://github.com/cyberbliss/kubectl-autocli"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberbliss/kubectl-autocli/releases/download/v0.1.0/kubectl-autocli_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "bd1e214b68ea7a3fa8dda92672b840fabf4fc900f64308a9b63eff7adc78dba6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/kubectl-autocli/releases/download/v0.1.0/kubectl-autocli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7e06fb07c6bd1a7678995840c6f2d2dd822e36b073d73597a2ac75c654f54ec6"
    end
  end

  def install
    bin.install "kubectl-ac"
  end

  test do
    system "#{bin}/kubectl-ac version"
  end
end
