# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAc < Formula
  desc "An autocomplete wrapper for kubectl"
  homepage "https://github.com/cyberbliss/kubectl-autocli"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberbliss/kubectl-autocli/releases/download/v0.2.1/kubectl-autocli_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "8d3b0874263d6feeec120bc2580701ef32fa47a713a9f44afab3d7a079116277"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/kubectl-autocli/releases/download/v0.2.1/kubectl-autocli_0.2.1_Linux_x86_64.tar.gz"
      sha256 "eb991c34675190e300fadb9af024591a9455a8cba562f60a647891813786814e"
    end
  end

  def install
    bin.install "kubectl-ac"
  end

  test do
    system "#{bin}/kubectl-ac version"
  end
end
