# This file was generated by GoReleaser. DO NOT EDIT.
class PowerlineGo < Formula
  desc "A beautiful and useful low-latency prompt for your shell, written in go"
  homepage "https://github.com/cyberbliss/powerline-go"
  version "2.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberbliss/powerline-go/releases/download/v2.1.0/powerline-go_2.1.0_Darwin_x86_64.tar.gz"
    sha256 "6355ff79d3461cc849d401869e75e788df1935982a9ba1d3c77a73101e0c912f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/powerline-go/releases/download/v2.1.0/powerline-go_2.1.0_Linux_x86_64.tar.gz"
      sha256 "16fd88df2d62c391488978641d5bb65dd57e83e868390592dd8aee0ab220cdd8"
    end
  end

  def install
    bin.install "powerline-go"
  end

  def caveats; <<~EOS
    You'll need to update your .zshrc/.bashrc/.profile. Deets in the readme: https://github.com/cyberbliss/powerline-go#bash
  EOS
  end

  test do
    system "#{bin}/powerline-go --version"
  end
end
