# This file was generated by GoReleaser. DO NOT EDIT.
class PowerlineGo < Formula
  desc "A beautiful and useful low-latency prompt for your shell, written in go"
  homepage "https://github.com/cyberbliss/powerline-go"
  version "2.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberbliss/powerline-go/releases/download/v2.1.1/powerline-go_2.1.1_Darwin_x86_64.tar.gz"
    sha256 "88c08c1cfcc26e1cf1fafe2ee0ec4db8c41444514e41c3fca41167806528139a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/powerline-go/releases/download/v2.1.1/powerline-go_2.1.1_Linux_x86_64.tar.gz"
      sha256 "d6229b72f2eb95b6cf694bd0921f30e25f37f6169d237fa0adc514949d88bfe0"
    end
  end

  def install
    bin.install "powerline-go"
  end

  def caveats; <<~EOS
    You'll need to update your .zshrc/.bashrc/.profile. Deets in the readme: https://github.com/cyberbliss/powerline-go#bash
  EOS
  end

  test do
    system "#{bin}/powerline-go --version"
  end
end
