# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelby < Formula
  desc "A fast and minimal Shell Prompt in Go"
  homepage "https://github.com/cyberbliss/shelby"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/shelby/releases/download/v2.0.0/shelby_2.0.0_Darwin_amd64.tar.gz"
      sha256 "fab7b28e17f53820f6062bee475b88ef935595ddbc93f108f3a87a6a3a031b68"

      def install
        bin.install "shelby"%
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/shelby/releases/download/v2.0.0/shelby_2.0.0_Linux_amd64.tar.gz"
      sha256 "11e0467b9bcb89f7ffe298dfa1ea49511ff38ad3ae42294a078ba7be8f7c3724"

      def install
        bin.install "shelby"%
      end
    end
  end
end
