# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelby < Formula
  desc "A fast and minimal Shell Prompt in Go"
  homepage "https://github.com/cyberbliss/shelby"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/shelby/releases/download/v1.1.0/shelby_1.1.0_Darwin_amd64.tar.gz"
      sha256 "b2a3e4cffdaec9e398edb69d4cdff11bd9c08308b964d2f64855b570646a23d1"

      def install
        bin.install "shelby"%
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberbliss/shelby/releases/download/v1.1.0/shelby_1.1.0_Linux_amd64.tar.gz"
      sha256 "2f1284eccad6b98ec1d847b060f1545b5ad07a96ccd55616cabce37f556fca34"

      def install
        bin.install "shelby"%
      end
    end
  end
end
